[tool.poetry]
name = "fresh-rotten-classificaton"
version = "0.1.0"
description = ""
authors = ["Andrey Timonin <an-timwork@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
pandas = "^2.3.3"
numpy = "^2.3.5"
ipykernel = "^7.1.0"
torch = "^2.9.1"
torchvision = "^0.24.1"
torchmetrics = "^1.8.2"
tqdm = "^4.67.1"
seaborn = "^0.13.2"
pre-commit = "^4.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
format = { docstring-code-format = true }

[tool.ruff.lint]
select = [
    # isort - джентельменский набор
    "I",
    # pycodestyle - джентельменский набор
    "E", "W",
    # Pyflakes - джентельменский набор
    "F",
    # pyupgrage
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # flake8-builtins
    "A",
    # flake8-return
    "RET",
    # flake8-use-pathlib
    "PTH",
    # flynt
    "FLY",
    # mccabe
    "C90",
    # NumPy-specific rules
    "NPY",
    # pep8-naming
    "N",
    # Ruff-specific rules
    "RUF",
    # Pyling - very strict, may be use when have enough time
    "PL",
    # refurb - also may be overwhelming
    "FURB"
]


pycodestyle = { max-doc-length = 105 }
